# Generated by Django 5.1.7 on 2025-06-01 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fynder', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fyndertypescollection',
            name='basic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.fynderbasictype'),
        ),
        migrations.AddField(
            model_name='fyndertypescollection',
            name='fynder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupfynderanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fynder.signupanswer'),
        ),
        migrations.AddField(
            model_name='signupfynderanswer',
            name='fynder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signupanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fynder.signupquestion'),
        ),
        migrations.AddField(
            model_name='temporarycode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
