# Generated by Django 5.1.7 on 2025-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fynder',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fynder',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
