# Generated by Django 5.1.7 on 2025-04-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0002_temporarycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fynder',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fynder',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_culture_heritage',
            field=models.FloatField(default=0.0, help_text='Interest level in Culture & Heritage (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_food_gastronomy',
            field=models.FloatField(default=0.0, help_text='Interest level in Food & Gastronomy (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_music_festivals',
            field=models.FloatField(default=0.0, help_text='Interest level in Music & Festivals (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_nature_outdoors',
            field=models.FloatField(default=0.0, help_text='Interest level in Nature & Outdoors (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_nightlife_party',
            field=models.FloatField(default=0.0, help_text='Interest level in Nightlife & Party (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_shopping_fashion',
            field=models.FloatField(default=0.0, help_text='Interest level in Shopping & Fashion (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_sport_adventure',
            field=models.FloatField(default=0.0, help_text='Interest level in Sport & Adventure (0-100)'),
        ),
        migrations.AddField(
            model_name='fynder',
            name='interest_wellness_spa',
            field=models.FloatField(default=0.0, help_text='Interest level in Wellness & Spa (0-100)'),
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fynder',
            name='food_preferences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fynder.foodpreferences'),
        ),
    ]
