# Generated by Django 5.1.7 on 2025-04-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0003_fynder_age_fynder_country_of_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fynder',
            name='food_preferences',
        ),
    ]
