# Generated by Django 5.1.7 on 2025-04-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0006_answer_question_alter_foodpreference_label_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodPreference',
            new_name='FynderFoodPreference',
        ),
    ]
