# Generated by Django 5.1.7 on 2025-04-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0008_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='SignUpAnswer',
        ),
        migrations.RenameModel(
            old_name='FynderAnswer',
            new_name='SignUpFynderAnswer',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='SignUpQuestion',
        ),
    ]
