# Generated by Django 5.1.7 on 2025-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0009_rename_answer_signupanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupquestion',
            name='max_number_of_answers',
            field=models.IntegerField(default=4),
        ),
    ]
