# Generated by Django 5.1.7 on 2025-05-24 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fynder', '0011_friendship'),
        ('info', '0007_fynderbasiccard_tag_locale_schedule_fyndertag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FynderCardsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.fynderbasiccard')),
                ('fynder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
