# Generated by Django 5.1.7 on 2025-04-28 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('trip_pax_type', models.CharField(choices=[('singolo', 'singolo'), ('amici', 'amici'), ('famiglia', 'famiglia'), ('coppia', 'coppia')], default='singolo', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_intensity', models.CharField(choices=[('poco', 'poco'), ('medio', 'medio'), ('tanto', 'tanto')], default='medio', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TripQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('pax', 'pax'), ('where', 'where'), ('start_date', 'start_date'), ('end_date', 'end_date'), ('budget', 'budget'), ('intensity', 'intensity')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TripFynder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fynder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_category', models.CharField(choices=[('Any', 'Any'), ('Vacanza al Mare', 'Vacanza al Mare'), ('Avventura in Montagna', 'Avventura in Montagna'), ('City Break Culturale', 'City Break Culturale'), ('City Break Locale', 'City Break Locale'), ('Viaggio Notturno e di Divertimento', 'Viaggio Notturno e di Divertimento'), ('Ritiro di Benessere in Natura', 'Ritiro di Benessere in Natura'), ('Viaggio di Lusso', 'Viaggio di Lusso'), ('Vacanza con Macchina', 'Vacanza con Macchina')], default='Any', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
