# Generated by Django 5.1.7 on 2025-06-01 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('pax', 'pax'), ('where', 'where'), ('from', 'from'), ('when', 'when'), ('budget', 'budget'), ('intensity', 'intensity'), ('fynder_basic_type', 'fynder_basic_type')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', max_length=20)),
                ('trip_pax_type', models.CharField(choices=[('singolo', 'singolo'), ('amici', 'amici'), ('famiglia', 'famiglia'), ('coppia', 'coppia')], default='singolo', max_length=20)),
                ('from_location', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_intensity', models.CharField(choices=[('poco', 'poco'), ('medio', 'medio'), ('tanto', 'tanto')], default='medio', max_length=20)),
                ('fynder_basic_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.fynderbasictype')),
            ],
        ),
        migrations.CreateModel(
            name='TripFynder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('fynder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripFynderAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TripQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_category', models.CharField(choices=[('Any', 'Any'), ('Vacanza al Mare', 'Vacanza al Mare'), ('Avventura in Montagna', 'Avventura in Montagna'), ('City Break Culturale', 'City Break Culturale'), ('City Break Locale', 'City Break Locale'), ('Viaggio Notturno e di Divertimento', 'Viaggio Notturno e di Divertimento'), ('Ritiro di Benessere in Natura', 'Ritiro di Benessere in Natura'), ('Viaggio di Lusso', 'Viaggio di Lusso'), ('Vacanza con Macchina', 'Vacanza con Macchina')], default='Any', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
