# Generated by Django 5.1.7 on 2025-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripquestion',
            name='question_type',
            field=models.CharField(choices=[('pax', 'pax'), ('where', 'where'), ('when', 'when'), ('budget', 'budget'), ('intensity', 'intensity')], max_length=20),
        ),
    ]
