# Generated by Django 5.1.7 on 2025-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_from_location_alter_tripquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripfynder',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
