# Generated by Django 5.1.7 on 2025-04-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('Cibo', 'Cibo'), ('Must see culturali', 'Must see culturali'), ('Eventi', 'Eventi'), ('Escursioni', 'Escursioni'), ('Museo', 'Museo'), ('Tour', 'Tour'), ('Parco', 'Parco'), ('Mercato', 'Mercato'), ('Negozi particolari', 'Negozi particolari'), ('Spa', 'Spa')], max_length=50)),
                ('generation_category', models.CharField(choices=[('Any', 'Any'), ('Vacanza al Mare', 'Vacanza al Mare'), ('Avventura in Montagna', 'Avventura in Montagna'), ('City Break Culturale', 'City Break Culturale'), ('City Break Locale', 'City Break Locale'), ('Viaggio Notturno e di Divertimento', 'Viaggio Notturno e di Divertimento'), ('Ritiro di Benessere in Natura', 'Ritiro di Benessere in Natura'), ('Viaggio di Lusso', 'Viaggio di Lusso')], max_length=50)),
                ('interest_culture_heritage', models.FloatField(default=0.0, help_text='Interest level in Culture & Heritage (0-100)')),
                ('interest_nature_outdoors', models.FloatField(default=0.0, help_text='Interest level in Nature & Outdoors (0-100)')),
                ('interest_food_gastronomy', models.FloatField(default=0.0, help_text='Interest level in Food & Gastronomy (0-100)')),
                ('interest_nightlife_party', models.FloatField(default=0.0, help_text='Interest level in Nightlife & Party (0-100)')),
                ('interest_wellness_spa', models.FloatField(default=0.0, help_text='Interest level in Wellness & Spa (0-100)')),
                ('interest_sport_adventure', models.FloatField(default=0.0, help_text='Interest level in Sport & Adventure (0-100)')),
                ('interest_music_festivals', models.FloatField(default=0.0, help_text='Interest level in Music & Festivals (0-100)')),
                ('interest_shopping_fashion', models.FloatField(default=0.0, help_text='Interest level in Shopping & Fashion (0-100)')),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('min_pax', models.PositiveIntegerField(blank=True, null=True)),
                ('max_pax', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
