# Generated by Django 5.1.7 on 2025-06-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaccommodation',
            name='search',
        ),
        migrations.RemoveField(
            model_name='savedaccommodation',
            name='fynder',
        ),
        migrations.DeleteModel(
            name='BookingSearch',
        ),
        migrations.DeleteModel(
            name='SavedAccommodation',
        ),
    ]
