# Generated by Django 5.1.7 on 2025-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_savedaccommodation_search_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fynderbasictype',
            name='interest_music_festivals',
        ),
        migrations.RemoveField(
            model_name='fynderbasictype',
            name='interest_shopping_fashion',
        ),
        migrations.RemoveField(
            model_name='fynderbasictype',
            name='interest_sport_adventure',
        ),
    ]
