# Generated by Django 5.1.7 on 2025-04-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_bookingsearch_savedaccommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsearch',
            name='accommodation_facilities',
            field=models.JSONField(help_text='Array of facility IDs', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='accommodation_types',
            field=models.JSONField(help_text='Array of accommodation type IDs', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='airport',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='brands',
            field=models.JSONField(help_text='Array of hotel chain IDs', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='cancellation_type',
            field=models.CharField(choices=[('free_cancellation', 'Free Cancellation'), ('non_refundable', 'Non Refundable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='children',
            field=models.JSONField(help_text='Array of children ages [5, 8]', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='credit_card_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='district',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='guest_allocation',
            field=models.JSONField(help_text='Exact allocation of guests to rooms', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='meal_plan',
            field=models.CharField(choices=[('all_inclusive', 'All Inclusive'), ('breakfast_included', 'Breakfast Included'), ('full_board', 'Full Board'), ('half_board', 'Half Board')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='min_review_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='payment_type',
            field=models.CharField(choices=[('pay_at_property', 'Pay at Property'), ('pay_online', 'Pay Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='region',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='room_facilities',
            field=models.JSONField(help_text='Array of room facility IDs', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='sort_by',
            field=models.CharField(choices=[('distance', 'Distance'), ('price', 'Price'), ('review_score', 'Review Score'), ('stars', 'Stars')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='sort_direction',
            field=models.CharField(choices=[('ascending', 'Ascending'), ('descending', 'Descending')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='stars',
            field=models.JSONField(help_text='Array of star ratings [4, 5]', null=True),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='travel_proud',
            field=models.BooleanField(default=False, help_text='LGBTQ+ friendly properties'),
        ),
        migrations.AddField(
            model_name='bookingsearch',
            name='twenty_four_hour_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedaccommodation',
            name='main_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedaccommodation',
            name='photos',
            field=models.JSONField(blank=True, help_text='Array of photo URLs', null=True),
        ),
        migrations.AlterField(
            model_name='bookingsearch',
            name='city_id',
            field=models.IntegerField(null=True),
        ),
    ]
