# Generated by Django 5.1.7 on 2025-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_bookingsearch_accommodation_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Cibo', 'Cibo'), ('Must see culturali', 'Must see culturali'), ('Eventi', 'Eventi'), ('Escursioni', 'Escursioni'), ('Museo', 'Museo'), ('Tour', 'Tour'), ('Parco', 'Parco'), ('Mercato', 'Mercato'), ('Negozi particolari', 'Negozi particolari'), ('Spa', 'Spa'), ('Spiaggia', 'Spiaggia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='generation_category',
            field=models.CharField(choices=[('Any', 'Any'), ('Vacanza al Mare', 'Vacanza al Mare'), ('Avventura in Montagna', 'Avventura in Montagna'), ('City Break Culturale', 'City Break Culturale'), ('City Break Locale', 'City Break Locale'), ('Viaggio Notturno e di Divertimento', 'Viaggio Notturno e di Divertimento'), ('Ritiro di Benessere in Natura', 'Ritiro di Benessere in Natura'), ('Viaggio di Lusso', 'Viaggio di Lusso'), ('Vacanza con Macchina', 'Vacanza con Macchina')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_culture_heritage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_food_gastronomy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_music_festivals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_nature_outdoors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_nightlife_party',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_shopping_fashion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_sport_adventure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_wellness_spa',
            field=models.IntegerField(default=0),
        ),
    ]
