# Generated by Django 5.1.7 on 2025-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_fynderbasictype_interest_music_festivals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=50, null=True),
        ),
    ]
