# Generated by Django 5.1.7 on 2025-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='interest_culture_heritage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_food_gastronomy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_music_festivals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_nature_outdoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_nightlife_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_shopping_fashion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_sport_adventure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interest_wellness_spa',
            field=models.BooleanField(default=False),
        ),
    ]
