# Generated by Django 5.1.7 on 2025-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_activity_interest_culture_heritage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_pax',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='min_pax',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='website',
        ),
        migrations.AddField(
            model_name='activity',
            name='productCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Cibo', 'Cibo'), ('Must see culturali', 'Must see culturali'), ('Eventi', 'Eventi'), ('Escursioni', 'Escursioni'), ('Museo', 'Museo'), ('Tour', 'Tour'), ('Parco', 'Parco'), ('Mercato', 'Mercato'), ('Negozi particolari', 'Negozi particolari'), ('Spa', 'Spa'), ('Spiaggia', 'Spiaggia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='generation_category',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Vacanza al Mare', 'Vacanza al Mare'), ('Avventura in Montagna', 'Avventura in Montagna'), ('City Break Culturale', 'City Break Culturale'), ('City Break Locale', 'City Break Locale'), ('Viaggio Notturno e di Divertimento', 'Viaggio Notturno e di Divertimento'), ('Ritiro di Benessere in Natura', 'Ritiro di Benessere in Natura'), ('Viaggio di Lusso', 'Viaggio di Lusso'), ('Vacanza con Macchina', 'Vacanza con Macchina')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
