# Generated by Django 5.1.7 on 2025-05-24 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_activity_address_remove_activity_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FynderBasicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('description', models.TextField()),
                ('interest_culture_heritage', models.FloatField(default=0.0, help_text='Interest level in Culture & Heritage (0-100)')),
                ('interest_nature_outdoors', models.FloatField(default=0.0, help_text='Interest level in Nature & Outdoors (0-100)')),
                ('interest_food_gastronomy', models.FloatField(default=0.0, help_text='Interest level in Food & Gastronomy (0-100)')),
                ('interest_nightlife_party', models.FloatField(default=0.0, help_text='Interest level in Nightlife & Party (0-100)')),
                ('interest_wellness_spa', models.FloatField(default=0.0, help_text='Interest level in Wellness & Spa (0-100)')),
                ('interest_sport_adventure', models.FloatField(default=0.0, help_text='Interest level in Sport & Adventure (0-100)')),
                ('interest_music_festivals', models.FloatField(default=0.0, help_text='Interest level in Music & Festivals (0-100)')),
                ('interest_shopping_fashion', models.FloatField(default=0.0, help_text='Interest level in Shopping & Fashion (0-100)')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Ristorante', 'Ristorante'), ('Street food', 'Street food'), ('Cucino a casa', 'Cucino a casa'), ('Bar caffetteria', 'Bar caffetteria'), ('Disco', 'Disco'), ('Pub', 'Pub'), ('Coffe shop', 'Coffe shop')], max_length=50, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Pasticceria', 'Pasticceria'), ('Aperitivi', 'Aperitivi'), ('Chioschi', 'Chioschi'), ('Enoteche', 'Enoteche'), ('Colazione', 'Colazione'), ('Brunch', 'Brunch'), ('Cena', 'Cena'), ('Pranzo', 'Pranzo'), ('Eventi', 'Eventi')], max_length=50, null=True)),
                ('cuisine_type', models.CharField(blank=True, choices=[('Italiana', 'Italiana'), ('Cinese', 'Cinese'), ('Giapponese', 'Giapponese'), ('Indiana', 'Indiana'), ('Americana', 'Americana'), ('Araba', 'Araba'), ('Mediterranea', 'Mediterranea'), ('Messicana', 'Messicana'), ('Pesce', 'Pesce'), ('Fast food', 'Fast food'), ('Pizzeria', 'Pizzeria')], max_length=50, null=True)),
                ('activity_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locale', to='info.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('fynder_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.fynderbasiccard')),
            ],
        ),
        migrations.CreateModel(
            name='FynderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fynder_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.fynderbasiccard')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.tag')),
            ],
        ),
    ]
