# Generated by Django 5.1.7 on 2025-05-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_fynderbasiccard_tag_locale_schedule_fyndertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
